version:  "3.7"
services: 
  devcontainer:
    build: .
    image: 3ddsg
    container_name: 3ddsg
    volumes:
      - /home/wenting/code/dsg_3d/.devcontainertest:/dsg_3d/.devcontainertest
      - /home/wenting/code/dsg_3d/code:/dsg_3d/code
      # - /home/wenting/code/dsg_3d/data/3RScan:/dsg_3d/data/3RScan
      # - /home/wenting/code/dsg_3d/data/ScanNetAll:/dsg_3d/data/ScanNet
      # - /home/wenting/code/dsg_3d/data/3RScanAll:/dsg_3d/data/3RScanAll
      - ~/.ssh:/root/.ssh:ro
      - ~/.gitconfig:/root/.gitconfig:ro
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    entrypoint: bash
    stdin_open: true
    tty: true
