version:  "3.7"
services: 
  devcontainer:
    build: .
    image: imagetest
    container_name: containertest
    volumes:
      - ~/DockerContainer/.devcontainertest:/workspace/.devcontainertest
      - ~/DockerContainer/code:/workspace/code
      # - /home/wenting/code/dsg_3d/data/3RScan:/dsg_3d/data/3RScan
      # - /home/wenting/code/dsg_3d/data/ScanNetAll:/dsg_3d/data/ScanNet
      # - /home/wenting/code/dsg_3d/data/3RScanAll:/dsg_3d/data/3RScanAll
      - ~/.ssh:/root/.ssh:ro
      - ~/.gitconfig:/root/.gitconfig:ro
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    entrypoint: bash
    stdin_open: true
    tty: true
