version:  "3.7"
services: 
  devcontainer:
    build: .
    image: imagetest
    container_name: containertest
    volumes:
      - ~/PATH/TO/DockerContainer/.devcontainer:/workspace/.devcontainer
      # - ~/DockerContainer/code:/workspace/code
      # - ~/DockerContainer/data:/workspace/data
      - ~/.ssh:/root/.ssh:ro
      - ~/.gitconfig:/root/.gitconfig:ro
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    entrypoint: bash
    stdin_open: true
    tty: true
