```
version:  "3.7"
services: 
  devcontainer:
    build: .
    image: imagetest #imagetest self-defined by Dockerfile but nvidia/cuda:12.2.0-runtime-ubuntu20.04 is a dowloaded image
    container_name: containertest
    volumes:
      - ~/PATH/TO/DockerContainer/.devcontainer:/workspace/.devcontainer
      # - ~/DockerContainer/code:/workspace/code
      # - ~/DockerContainer/data:/workspace/data
      - ~/.ssh:/root/.ssh:ro
      - ~/.gitconfig:/root/.gitconfig:ro
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    entrypoint: bash
    stdin_open: true
    tty: true
```
```    
version:  "3.7"
services: 
  devcontainer:
    build: .
    image: imagetest
    container_name: containertest
    volumes:
      - ~/PATH/TO/DockerContainer/.devcontainer:/workspace/.devcontainer
      # - ~/DockerContainer/code:/workspace/code
      # - ~/DockerContainer/data:/workspace/data
      - ~/.ssh:/root/.ssh:ro
      - ~/.gitconfig:/root/.gitconfig:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids : ['0','1'] # if there are multi gpus
              capabilities: [gpu]

    entrypoint: bash
    stdin_open: true
    tty: true
```    
    
```
version:  "3.7"
services: 
  devcontainer:
    build: .
    image: imagetest
    container_name: containertest
    volumes:
      - ~/PATH/TO/DockerContainer/.devcontainer:/workspace/.devcontainer
      # - ~/DockerContainer/code:/workspace/code
      # - ~/DockerContainer/data:/workspace/data
      - ~/.ssh:/root/.ssh:ro
      - ~/.gitconfig:/root/.gitconfig:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    entrypoint: bash
    stdin_open: true
    tty: true
  ```
